package com.juansecu.opentoonix.rooms.enums;

public enum ERoom {
    BALOONS_A("baloons_a"),
    BALOONS_B("baloons_b"),
    BALOONS_C("baloons_c"),
    BALOONS_D("baloons_d"),
    BALOONS_E("baloons_e"),
    BEACH_A("beach_a"),
    BEACH_B("beach_b"),
    BEACH_C("beach_c"),
    BEN_10_A("ben10_a"),
    BEN_10_B("ben10_b"),
    BEN_10_C("ben10_c"),
    BEN_10_D("ben10_d"),
    BEN_10_E("ben10_e"),
    BEN_10_F("ben10_f"),
    BRAZIL_BTS_2013_A("brazilbts2013_a"),
    BUILDING_A("building_a"),
    BUILDING_B("building_b"),
    BUILDING_C("building_c"),
    BUILDING_D("building_d"),
    BUILDING_E("building_e"),
    CARRERA_2012_A("carrera2012_a"),
    CAVE_A("cave_a"),
    CAVE_B("cave_b"),
    CAVE_C("cave_c"),
    CAVE_D("cave_d"),
    CAVE_E("cave_e"),
    CHICLE_SPLOT_A("chiclesplot_a"),
    CHICLE_SPLOT_B("chiclesplot_b"),
    CHICLE_SPLOT_C("chiclesplot_c"),
    CHOCOKRISPIS_A("chocokrispis_a"),
    CHOCOKRISPIS_B("chocokrispis_b"),
    CLOUDS_A("clouds_a"),
    CLOUDS_B("clouds_b"),
    CLOUDS_C("clouds_c"),
    CLOUDS_D("clouds_d"),
    COPATOON("copatoon"),
    DESERT_A("desert_a"),
    DESERT_B("desert_b"),
    DESERT_C("desert_c"),
    DESERT_D("desert_d"),
    EARTH_DAY("earthday"),
    ELEVATOR("elevator"),
    GAME_ARBOL("game_arbol"),
    GAME_MAIZ("game_maiz"),
    GAME_MOSCAS("game_moscas"),
    GAME_OMNITRIX("game_omnitrix"),
    GAME_PATITAS("game_patitas"),
    GAME_PIPES("game_pipes"),
    GAME_TOTEMS("game_totems"),
    GAME_VAN("game_van"),
    GIRAFFAS_A("giraffas_a"),
    GIRAFFAS_B("giraffas_b"),
    GIRAFFAS_C("giraffas_c"),
    GENERATOR_REX_A("grex_a"),
    GENERATOR_REX_B("grex_b"),
    LOVY("lovy"),
    MAX_STEEL_A("maxsteel_a"),
    MAX_STEEL_B("maxsteel_b"),
    MAX_STEEL_C("maxsteel_c"),
    MONSTER_HIGH_A("monsterh_a"),
    MONSTER_HIGH_B("monsterh_b"),
    MONSTER_HIGH_C("monsterh_c"),
    PAPER_A("paper_a"),
    PAPER_B("paper_b"),
    PAPER_C("paper_c"),
    PAPER_D("paper_d"),
    PAPER_E("paper_e"),
    PATITAS_A("patitas_a"),
    PATITAS_B("patitas_b"),
    PATITAS_C("patitas_c"),
    PEGAJOSAS_A("pegajosas_a"),
    PEGAJOSAS_B("pegajosas_b"),
    PEGAJOSAS_C("pegajosas_c"),
    SHOP_A("shop_a"),
    WOODS_A("woods_a"),
    WOODS_B("woods_b"),
    WOODS_C("woods_c"),
    WOODS_D("woods_d"),
    XALINGO_A("xalingo_a"),
    XALINGO_B("xalingo_b"),
    XALINGO_C("xalingo_c");

    final String roomName;

    ERoom(String roomName) {
        this.roomName = roomName;
    }

    public String getRoomName() {
        return this.roomName;
    }
}
